# Generated by Django 5.1.2 on 2024-11-16 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_payment_link_to_payment_payment_session_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"verbose_name": "Оплата", "verbose_name_plural": "Оплаты"},
        ),
    ]
