# Generated by Django 5.1.2 on 2024-11-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_payment_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cash", "Оплата наличными"),
                    ("transfer", "Оплата переводом"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
